import type {
  Contato,
  Conversa,
  ConsumoIa,
  EtapaFunil,
  IndicadoresCrm,
  Oportunidade,
  PontoGrafico,
  Tarefa,
} from "@/tipos/crm";

export const etapasFunilSimuladas: EtapaFunil[] = [
  { id: "novo-lead", nome: "Novo lead", ordem: 1, cor: "#2563EB" },
  { id: "em-contato", nome: "Em contato", ordem: 2, cor: "#0F3D5E" },
  { id: "qualificado", nome: "Qualificado", ordem: 3, cor: "#D97706" },
  { id: "proposta-enviada", nome: "Proposta enviada", ordem: 4, cor: "#7C3AED" },
  { id: "convertido", nome: "Convertido", ordem: 5, cor: "#16A34A" },
  { id: "perdido", nome: "Perdido", ordem: 6, cor: "#DC2626" },
];

export const oportunidadesSimuladas: Oportunidade[] = [
  {
    id: "opp-1",
    idContato: "contato-1",
    nomeContato: "Camila Rocha",
    nomeEmpresa: "Bistrô Jardim",
    telefone: "+55 81 98888-1201",
    idEtapa: "novo-lead",
    idResponsavel: "usuario-1",
    nomeResponsavel: "Marina Costa",
    valorEstimado: 2400,
    origem: "WhatsApp",
    etiquetas: [{ id: "tag-1", nome: "Restaurante", cor: "#2563EB" }],
    ultimaInteracaoEm: new Date("2026-08-04T09:20:00"),
    proximaTarefa: {
      id: "tar-1",
      titulo: "Enviar cardápio de automações",
      vencimentoEm: new Date("2026-08-04T16:00:00"),
      prioridade: "MEDIA",
      concluida: false,
    },
    situacao: "ABERTA",
  },
  {
    id: "opp-2",
    idContato: "contato-2",
    nomeContato: "Dr. Felipe Moura",
    nomeEmpresa: "Clínica Santé",
    telefone: "+55 11 97777-2102",
    idEtapa: "em-contato",
    idResponsavel: "usuario-2",
    nomeResponsavel: "Rafael Lima",
    valorEstimado: 5200,
    origem: "Indicação",
    etiquetas: [{ id: "tag-2", nome: "Clínica", cor: "#16A34A" }],
    ultimaInteracaoEm: new Date("2026-08-03T15:12:00"),
    proximaTarefa: {
      id: "tar-2",
      titulo: "Agendar demonstração",
      vencimentoEm: new Date("2026-08-05T10:00:00"),
      prioridade: "ALTA",
      concluida: false,
    },
    situacao: "ABERTA",
  },
  {
    id: "opp-3",
    idContato: "contato-3",
    nomeContato: "Juliana Matos",
    nomeEmpresa: "Loja Essenza",
    telefone: "+55 21 96666-3344",
    idEtapa: "qualificado",
    idResponsavel: "usuario-1",
    nomeResponsavel: "Marina Costa",
    valorEstimado: 3800,
    origem: "Instagram",
    etiquetas: [{ id: "tag-3", nome: "Varejo", cor: "#D97706" }],
    ultimaInteracaoEm: new Date("2026-08-02T11:30:00"),
    situacao: "ABERTA",
  },
  {
    id: "opp-4",
    idContato: "contato-4",
    nomeContato: "Renato Alves",
    nomeEmpresa: "Prime Serviços",
    telefone: "+55 31 95555-8899",
    idEtapa: "proposta-enviada",
    idResponsavel: "usuario-3",
    nomeResponsavel: "Bianca Souza",
    valorEstimado: 7600,
    origem: "Site",
    etiquetas: [{ id: "tag-4", nome: "Serviços", cor: "#0F3D5E" }],
    ultimaInteracaoEm: new Date("2026-08-01T17:45:00"),
    situacao: "ABERTA",
  },
  {
    id: "opp-5",
    idContato: "contato-5",
    nomeContato: "Paula Nunes",
    nomeEmpresa: "Dental Norte",
    telefone: "+55 85 94444-8721",
    idEtapa: "convertido",
    idResponsavel: "usuario-2",
    nomeResponsavel: "Rafael Lima",
    valorEstimado: 6100,
    origem: "WhatsApp",
    etiquetas: [{ id: "tag-2", nome: "Clínica", cor: "#16A34A" }],
    ultimaInteracaoEm: new Date("2026-07-31T14:15:00"),
    situacao: "GANHA",
  },
  {
    id: "opp-6",
    idContato: "contato-6",
    nomeContato: "Eduardo Pires",
    nomeEmpresa: "Sabor Mineiro",
    telefone: "+55 31 93333-4490",
    idEtapa: "perdido",
    idResponsavel: "usuario-1",
    nomeResponsavel: "Marina Costa",
    valorEstimado: 1900,
    origem: "Feira",
    etiquetas: [{ id: "tag-1", nome: "Restaurante", cor: "#2563EB" }],
    ultimaInteracaoEm: new Date("2026-07-30T08:50:00"),
    situacao: "PERDIDA",
  },
];

export const contatosSimulados: Contato[] = oportunidadesSimuladas.map((oportunidade) => ({
  id: oportunidade.idContato,
  nome: oportunidade.nomeContato,
  telefone: oportunidade.telefone,
  email: `${oportunidade.nomeContato.toLowerCase().split(" ")[0]}@exemplo.com`,
  empresa: oportunidade.nomeEmpresa,
  origem: oportunidade.origem,
  idResponsavel: oportunidade.idResponsavel,
  nomeResponsavel: oportunidade.nomeResponsavel,
  etiquetas: oportunidade.etiquetas,
  ultimaInteracaoEm: oportunidade.ultimaInteracaoEm,
  situacao: "ATIVO",
}));

export const tarefasSimuladas: Tarefa[] = [
  {
    id: "tar-1",
    titulo: "Enviar cardápio de automações",
    idContato: "contato-1",
    nomeContato: "Camila Rocha",
    idOportunidade: "opp-1",
    nomeOportunidade: "Bistrô Jardim",
    idResponsavel: "usuario-1",
    nomeResponsavel: "Marina Costa",
    prioridade: "MEDIA",
    vencimentoEm: new Date("2026-08-04T16:00:00"),
    situacao: "PENDENTE",
  },
  {
    id: "tar-2",
    titulo: "Agendar demonstração",
    idContato: "contato-2",
    nomeContato: "Dr. Felipe Moura",
    idOportunidade: "opp-2",
    nomeOportunidade: "Clínica Santé",
    idResponsavel: "usuario-2",
    nomeResponsavel: "Rafael Lima",
    prioridade: "ALTA",
    vencimentoEm: new Date("2026-08-05T10:00:00"),
    situacao: "PENDENTE",
  },
  {
    id: "tar-3",
    titulo: "Retornar sobre orçamento",
    idContato: "contato-4",
    nomeContato: "Renato Alves",
    idOportunidade: "opp-4",
    nomeOportunidade: "Prime Serviços",
    idResponsavel: "usuario-3",
    nomeResponsavel: "Bianca Souza",
    prioridade: "ALTA",
    vencimentoEm: new Date("2026-08-03T11:00:00"),
    situacao: "ATRASADA",
  },
  {
    id: "tar-4",
    titulo: "Validar plano de implantação",
    idContato: "contato-5",
    nomeContato: "Paula Nunes",
    idOportunidade: "opp-5",
    nomeOportunidade: "Dental Norte",
    idResponsavel: "usuario-2",
    nomeResponsavel: "Rafael Lima",
    prioridade: "BAIXA",
    vencimentoEm: new Date("2026-08-01T09:00:00"),
    situacao: "CONCLUIDA",
  },
];

export const conversasSimuladas: Conversa[] = [
  {
    id: "conv-1",
    idContato: "contato-1",
    nomeContato: "Camila Rocha",
    telefone: "+55 81 98888-1201",
    canal: "WHATSAPP",
    situacao: "IA_ATIVA",
    etiquetas: [{ id: "tag-1", nome: "Restaurante", cor: "#2563EB" }],
    ultimaMensagem: "Quero entender os planos para restaurantes.",
    ultimaMensagemEm: new Date("2026-08-04T09:22:00"),
    mensagens: [
      {
        id: "msg-1",
        autor: "CLIENTE",
        conteudo: "Bom dia, vocês atendem restaurante?",
        enviadaEm: new Date("2026-08-04T09:15:00"),
        status: "LIDA",
      },
      {
        id: "msg-2",
        autor: "IA",
        conteudo: "Atendemos sim. Posso te mostrar fluxos para reservas, pedidos e retorno de clientes.",
        enviadaEm: new Date("2026-08-04T09:16:00"),
        status: "ENTREGUE",
      },
    ],
  },
  {
    id: "conv-2",
    idContato: "contato-2",
    nomeContato: "Dr. Felipe Moura",
    telefone: "+55 11 97777-2102",
    canal: "WHATSAPP",
    situacao: "HUMANO",
    etiquetas: [{ id: "tag-2", nome: "Clínica", cor: "#16A34A" }],
    ultimaMensagem: "Podemos marcar uma demonstração amanhã?",
    ultimaMensagemEm: new Date("2026-08-03T15:12:00"),
    mensagens: [
      {
        id: "msg-3",
        autor: "ATENDENTE",
        conteudo: "Amanhã às 10h funciona para você?",
        enviadaEm: new Date("2026-08-03T15:12:00"),
        status: "LIDA",
      },
    ],
  },
  {
    id: "conv-3",
    idContato: "contato-3",
    nomeContato: "Juliana Matos",
    telefone: "+55 21 96666-3344",
    canal: "WHATSAPP",
    situacao: "IA_ATIVA",
    etiquetas: [{ id: "tag-3", nome: "Varejo", cor: "#D97706" }],
    ultimaMensagem: "Gostaria de saber mais sobre automações.",
    ultimaMensagemEm: new Date("2026-08-02T11:30:00"),
    mensagens: [
      {
        id: "msg-4",
        autor: "CLIENTE",
        conteudo: "Gostaria de saber mais sobre automações para loja.",
        enviadaEm: new Date("2026-08-02T11:30:00"),
        status: "LIDA",
      },
    ],
  },
  {
    id: "conv-4",
    idContato: "contato-4",
    nomeContato: "Renato Alves",
    telefone: "+55 31 95555-8899",
    canal: "WHATSAPP",
    situacao: "AGUARDANDO",
    etiquetas: [{ id: "tag-4", nome: "Serviços", cor: "#0F3D5E" }],
    ultimaMensagem: "Tudo certo, aguardo o retorno!",
    ultimaMensagemEm: new Date("2026-08-01T17:45:00"),
    mensagens: [
      {
        id: "msg-5",
        autor: "CLIENTE",
        conteudo: "Tudo certo, aguardo o retorno!",
        enviadaEm: new Date("2026-08-01T17:45:00"),
        status: "ENTREGUE",
      },
    ],
  },
  {
    id: "conv-5",
    idContato: "contato-5",
    nomeContato: "Paula Nunes",
    telefone: "+55 85 94444-8721",
    canal: "WHATSAPP",
    situacao: "HUMANO",
    etiquetas: [{ id: "tag-2", nome: "Clínica", cor: "#16A34A" }],
    ultimaMensagem: "Você: Enviamos o material solicitado.",
    ultimaMensagemEm: new Date("2026-07-31T14:15:00"),
    mensagens: [
      {
        id: "msg-6",
        autor: "ATENDENTE",
        conteudo: "Enviamos o material solicitado.",
        enviadaEm: new Date("2026-07-31T14:15:00"),
        status: "LIDA",
      },
    ],
  },
];

export const indicadoresCrmSimulados: IndicadoresCrm = {
  oportunidadesAbertas: 4,
  valorTotalNegociacao: 19000,
  oportunidadesGanhas: 12,
  taxaConversao: 0.31,
  tarefasAtrasadas: 3,
};

export const consumoSimulado: ConsumoIa = {
  plano: "Profissional",
  periodo: "Agosto de 2026",
  limite: 2500000,
  percentualUtilizado: 0.62,
  tokensEntrada: 840000,
  tokensSaida: 710000,
  chamadasIa: 8420,
  mensagensProcessadas: 18540,
  custoEstimado: 1240,
  custoPorConversa: 1.92,
};

export const oportunidadesPorEtapaSimuladas: PontoGrafico[] = etapasFunilSimuladas.map((etapa) => ({
  nome: etapa.nome,
  valor: oportunidadesSimuladas.filter((oportunidade) => oportunidade.idEtapa === etapa.id).length,
}));

export const conversasPorDiaSimuladas: PontoGrafico[] = [
  { nome: "Seg", valor: 142 },
  { nome: "Ter", valor: 168 },
  { nome: "Qua", valor: 154 },
  { nome: "Qui", valor: 196 },
  { nome: "Sex", valor: 211 },
  { nome: "Sáb", valor: 124 },
  { nome: "Dom", valor: 88 },
];

export const consumoPorDiaSimulado: PontoGrafico[] = [
  { nome: "01/08", valor: 116000, secundario: 92 },
  { nome: "02/08", valor: 148000, secundario: 121 },
  { nome: "03/08", valor: 172000, secundario: 136 },
  { nome: "04/08", valor: 104000, secundario: 84 },
];
